language: node_js
node_js:
- v6
- v7
before_install: npm install -g codecov
after_success:
- rm -rf ./coverage/clover.xml ./coverage/coverage-final.json ./coverage/lcov.info ./coverage/lcov-report
- codecov -e TRAVIS_NODE_VERSION
- npm run doc
deploy:
  provider: npm
  email: hourliert@gmail.com
  api_key:
    secure: jXJ83NIxh5i1R6B/Iab63QRRBUw6axuCzvEeDMrys6d8E+0kNbO54D7xResoYUv45LevpNPz93D7OFBmVYd0iwX25i5hii0jEUjM2KpoIv8w7H89RyRMbK81xdOMrQbbOwX3tgAr//CyeaeyYxDubDLJf8WwDSJzCVOO4Ex5a74h5dqoGO51wEHw931ufojVtKHoKHK6b/OsPHPxVzozg/WHC+C/gCYGmDyRCmfPiGfoNGWW08QIRj6iuMw//vHmSc5x8/p/0s1xA0D+RKvJddBQhzQPBvwfEKCuHeUgUBnnhwECGjaDUIItirUJFw5YcfGVPOZuBLnUKXC3hexyzrmOuKfFuvjSDuqlOSFLTBpsd7JPDB/jD6MXPtlwhNZa7DxVgpkXMhk9TmLCAoAOuF8cu369NFx3sUYDg825BMvb8dxkvN6SsxTdiyGSNmhOr0EUmvrGEdZ3xmWinb+oJlNy3Ckg5UXFt6IismTqvS5wkh+sDW+9ZOA3tc6oy08d0oOF+AztUP3lxkWYa54lNCO2tcuKPMrj1zWxhw1Etmr3mb6rOfSpdDcBh5Zg1gz9m1fBiAbbcJA/knBkhwtjaPyNyB1BzLWmjCpHuAYSN39Jojt0WRz/YO4Jfy+UcZhxlQl5kmdf0gSBEiGyHEjlz2csTia4qcMUnN9xL5ub2WU=
  on:
    tags: true
    repo: FoodMeUp/redux-crud-observable
